#!/bin/bash

npm run lint
RESULT="$?"
if [ 0 -ne "$RESULT" ]
then
    echo "Linter errors! Exit status $RESULT"
    exit 1
fi

npm run test:single
RESULT="$?"
if [ 0 -ne "$RESULT" ]
then
    echo "Unit tests errors! Exit status $RESULT"
    exit 1
fi
